config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'puzzles#index'

  get '/roll', to: 'static_pages#roll'

  root 'puzzles#index'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  namespace :api, defaults: {format: :json} do
    resources :puzzles
  end

  get 'puzzles/:id/solve' => 'puzzles#solve'
  get 'puzzles/:id/display_original' => 'puzzles#display_original'
  get 'puzzles/:id/display_solution' => 'puzzles#display_solution'
  get 'puzzles/:id/revert_puzzle' => 'puzzles#revert_puzzle'
  resources :puzzles
  get  '/puzzles', to: 'puzzles#index'
end

app/models/puzzle.rb
class Puzzle < ActiveRecord::Base
  include Solver
  include BoardInfo

  serialize :board
  serialize :original
  serialize :solution

  def board=(board)
    super(board.map(&:to_i))
  end

  def setup_puzzle
    self.original = board
    self.original
    self.solution = solve_puzzle
    self.board = self.original
    self
  end

  def display
    board.each_slice(9) do |row|
      puts row.join
    end
    nil
  end

  def blank_board
    board=Array.new(81, 0)
  end

  def revert
    board = original
  end

  def given
    original.reject { |num| num == 0 }.count
  end

end

app/controllers/api/puzzles_controller.rb
class Api::PuzzlesController < ApplicationController
include PuzzlesHelper

  #creates a hash [square, place in square] => value

  def index
    @puzzles = Puzzle.all
    render json: @puzzles
  end

  def create
    @puzzle = Puzzle.new(puzzle_params)
    @puzzle.setup_puzzle
    if @puzzle.save
      render json: @puzzle
    else
      render json: @puzzle.errors.fullmessages
    end
  end

  def show
    find_puzzle
    render json: @puzzle
  end

  def update
    find_puzzle
    @puzzle.update(puzzle_params)
    render json: @puzzle
  end

  def destroy
    # find_puzzle
    # @puzzle.destroy
    # redirect_to puzzles_path
  end

  private

  def puzzle_params
    params.require(:puzzle).permit(board: [])
  end
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
include PuzzlesHelper

  #creates a hash [square, place in square] => value
  def index
  end
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
 
  def puzzle_params
    params.require(:puzzle).permit(:"0, 0", :"0, 1", :"0, 2", :"0, 3", :"0, 4", :"0, 5", :"0, 6", :"0, 7", :"0, 8", :"1, 0", :"1, 1", :"1, 2", :"1, 3", :"1, 4", :"1, 5", :"1, 6", :"1, 7", :"1, 8", :"2, 0", :"2, 1", :"2, 2", :"2, 3", :"2, 4", :"2, 5", :"2, 6", :"2, 7", :"2, 8", :"3, 0", :"3, 1", :"3, 2", :"3, 3", :"3, 4", :"3, 5", :"3, 6", :"3, 7", :"3, 8", :"4, 0", :"4, 1", :"4, 2", :"4, 3", :"4, 4", :"4, 5", :"4, 6", :"4, 7", :"4, 8", :"5, 0", :"5, 1", :"5, 2", :"5, 3", :"5, 4", :"5, 5", :"5, 6", :"5, 7", :"5, 8", :"6, 0", :"6, 1", :"6, 2", :"6, 3", :"6, 4", :"6, 5", :"6, 6", :"6, 7", :"6, 8", :"7, 0", :"7, 1", :"7, 2", :"7, 3", :"7, 4", :"7, 5", :"7, 6", :"7, 7", :"7, 8", :"8, 0", :"8, 1", :"8, 2", :"8, 3", :"8, 4", :"8, 5", :"8, 6", :"8, 7", :"8, 8")
  end

  def find_puzzle
    @puzzle=Puzzle.find(params[:id])
  end

end

app/views/puzzles/_displayboard.html.erb
<div id = "puzzle">
<% edit_form ||= nil %>
<% solve_form ||= nil %>
<% create_form ||= nil %>
<% from_hash ||= nil %>
<%= form_for @puzzle do |f| %>
<table id="main">
  <% (0..8).each do |square| %>
    <% if square % 3 == 0 %>
      <tr>
    <%end%>
    <td>
      <table id="inner">
        <% (0..8).each do |place| %>
          <% if place % 3 == 0 %>
            <tr>
          <% end %>
              <td>
                <% location = 9*square + place %>
                  <% if edit_form  %>
                      <%= f.text_field "#{square}, #{place}", value: @puzzle.send("#{square}, #{place}"), :class => "square" %>
                  <% elsif solve_form %>
                    <% if @puzzle.send("#{square}, #{place}")=="" %>
                       <%= f.text_field "#{square}, #{place}", :class => "square" %>
                    <% else %>
                      <%= @puzzle.send("#{square}, #{place}") %>
                    <%end %>
                  <% elsif from_hash %>
                    <% values = @puzzle.send(from_hash) %>
                    <%= values["#{square}, #{place}"]%>
                  <% else %>
                    <%= @puzzle.send("#{square}, #{place}") %>
                  <% end %>
              </td>
          <% if place % 3 == 2 %>
            </tr>
          <% end %>
        <% end %>
      </table>
    </td>
    <% if square % 3 == 2 %>
      </tr>
    <%end%>
  <% end %>
</table>
<% if solve_form %>
  <%= f.submit("Update") %>
<% elsif edit_form %>
  <%= f.submit("Edit") %>
<% elsif create_form %>
  <%= f.submit("Create") %>
<% end %>

<% end %>
</div>

app/views/puzzles/_puzzle_menu.html.erb
<div id="menu">
  <p><%= link_to "<< All", puzzles_path, :title => "View all puzzles." %>
  </p>
  <p><%= link_to "View", puzzle_path(@puzzle), :title => "View the puzzle." %>
  </p>
  <p><%= link_to "Solve", "/puzzles/#{@puzzle.id}/solve", :title => "Complete unknown squares." %>
  </p>
  <p><%= link_to "Original", "/puzzles/#{@puzzle.id}/display_original" , :title => "View the original puzzle."%>
  </p>
  <p><%= link_to "Solution", "/puzzles/#{@puzzle.id}/display_solution", :title => "View the solution." %>
  </p>
  <p><%= link_to "Revert", "/puzzles/#{@puzzle.id}/revert_puzzle", :title => "Change puzzle back to original.", data: {confirm: "Really revert this puzzle?"} %>
  </p>
  <p><%= link_to "Edit", edit_puzzle_path(@puzzle) , :title => "Edit all values."%>
  </p>
  <p><%= link_to "Delete", puzzle_path(@puzzle),  method: :delete, data: {confirm: "Really delete this puzzle?"} , :title => "Delete the puzzle."%>
</p>
</div>

app/views/puzzles/display_original.html.erb
<% provide(:title, "Original") %>
<div id="content">
<h1> <%= header("Original") %> </h1>
<%= render :partial => 'displayboard', :locals => { :from_hash => "original" } %>
</div>
<%= render :partial => "puzzle_menu" %>

app/views/puzzles/display_solution.html.erb
<% provide(:title, "Solution") %>
<div id="content">
<h1> <%= header("Solution") %> </h1>
<%= render :partial => 'displayboard', :locals => { :from_hash => "solution" } %>
</div>
<%= render :partial => "puzzle_menu" %>

app/views/puzzles/edit.html.erb
<% provide(:title, "Edit") %>
<div id="content">
<h1> <%= header("Edit") %> </h1>
<%= render :partial => 'displayboard', :locals => {:edit_form => true , :board => @puzzle.board} %>
</div>
<%= render :partial => "puzzle_menu" %>

app/views/puzzles/index.html.erb
<section class="content">
</section>

app/views/puzzles/new.html.erb
<%# provide(:title, "New") %>
<div id="content">
<h1> <%#= header("New") %> </h1>
<%#= render :partial => 'displayboard', :locals => {:edit_form => true , :board => @puzzle.blank_board} %>
<p>
<%#= link_to "<< All Puzzles", puzzles_path %>
</p>
</div>

app/views/puzzles/show.html.erb
<% provide(:title, "View") %>

<div id="content">
<h1> <%= header("View") %> </h1>

<%= render :partial => 'displayboard', :locals => { :board => @puzzle.board} %>
</div>
<%= render :partial => "puzzle_menu" %>

app/views/puzzles/solve.html.erb
<% provide(:title, "Solve") %>

<div id="content">
<h1> <%= header("Solve") %> </h1>
<%= render :partial => 'displayboard', :locals => {:solve_form => true , :board => @puzzle.board} %>
</div>
<%= render :partial => "puzzle_menu" %>